In [9]:
import numpy as np

def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [15]:
I = np.array([0.9, 0.1, 0.8])
W_i = np.array([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])
W_h = np.array([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])

A1 = np.dot( W_i,I)
print(A1)
Z1 = sigmoid(A1)
print(Z1)
A2 = np.dot(W_h, Z1)
print(A2)
Z2 = sigmoid(A2)
Y = Z2
print(Y)

[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
[1.16 0.42 0.62]
[0.76133271 0.60348325 0.65021855]
[0.97594736 0.88858496 1.25461119]
[0.72630335 0.70859807 0.77809706]


# 201601769 나요한
