# 1번 문제 : Chapter 9 (forward)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

def sigmoid(x):
    return 1/(1 + np.exp(-x))

Populating the interactive namespace from numpy and matplotlib


In [2]:
I = np.array([0.9, 0.1, 0.8])

W_ih = np.array([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])
W_ho = np.array([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])

A1 = np.dot( W_ih,I)
Z1 = sigmoid(A1)
A2 = np.dot(W_ho, Z1)
Z2 = sigmoid(A2)
Y = Z2

print(I)
print("forward:",A1)
print("sigmoid:",Z1)
print("forward:", A2)
print("result:", Y)

[0.9 0.1 0.8]
forward: [1.16 0.42 0.62]
sigmoid: [0.76133271 0.60348325 0.65021855]
forward: [0.97594736 0.88858496 1.25461119]
result: [0.72630335 0.70859807 0.77809706]


# 2번 문제 : Chapter 12 (backward)

In [3]:
E_out = np.array([0.8, 0.5])
W_1 = np.array([[3.0, 2.0], [1.0, 7.0]])
#W_1 = W_1.T
W_2 = np.array([[2.0, 3.0], [1.0, 4.0]])
#W_2 = W_2.T

def backward(W, E):
    #E1 = W[0,0]/(W[0,0] + W[1,0]) * E[0] + W[0,1]/(W[0,1] + W[1,1]) * E[1]
    #E2 = W[1,0]/(W[0,0] + W[1,0]) * E[0] + W[1,1]/(W[0,1] + W[1,1]) * E[1]
    #e = np.array([E1, E2])
    e = np.dot(W.T, E)/(np.sum(W)/2)
    return e

E_hidden = backward(W_2, E_out)
E_input = backward(W_1, E_hidden)

print("E_hidden:", E_hidden)
print("E_input:", E_input)

#왜 e = np.dot(W.T, E) 이걸로 하면 값이 다를까? 행렬곱을 이용한 역전파의 경우니까 다른게 나오는건가?
#E_hidden: [0.42 0.88]
#E_input: [0.362 0.938]
#해결:웨이트값을 전체 더해서 /2 하니까 직접한 계산한 값과 같아짐. 3x3에서도 사용가능!

E_hidden: [0.42 0.88]
E_input: [0.32923077 1.07692308]


# 3번 문제 : Chapter 15 (update)

In [4]:
import math

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def logit(x):
    return np.log(x/(1-x))
x = np.linspace(0.01, 0.99, num= 100)
#plt.plot(logit(x))

def forward(W, I):
    A1 = np.dot(W,I)
    return sigmoid(A1)

def backward(W, E):
    e = np.dot(W.T, E)/(np.sum(W)/2)
    return e

O_j = np.array([0.4, 0.5])
E_k = np.array([0.8, 0.5])
W_1 = np.array([[1.0, 2.0], [1.0, 7.0]])
W_2 = np.array([[2.0, 3.0], [1.0, 4.0]])
I = np.dot(np.linalg.inv(W_1),logit(O_j))

print("----  I  ---------------")
print(I)
print("---- W_1 ---------------")
print(W_1)
print("---- W_2 ---------------")
print(W_2)

O_j = forward(W_1, I)
O_k = forward(W_2, O_j)
lr = 0.1

Update_val = lr*(-E_k * forward(W_2, O_j)*(1- forward(W_2, O_j)) *O_j.T)
W_2 = W_2 - Update_val

print("----E_h uppdate_val --------")
print(Update_val)
print("---- W_2 Answer ------------")
print(W_2)

E_j = np.dot(W_2.T, E_k)/(np.sum(W_2)/2)
Update_val = lr*(-E_j * O_j*(1- O_j) * I.T)
W_1 = W_1 - Update_val

print("----E_i Update_val --------")
print(Update_val)
print("---- W_1 Answer ------------")
print(W_1)

#inverse sigmoid통과시켜서를 써서 입력값 초기값
#입력값이 없어서 W_1값을 업데이트 할수 없는데 어떻게 해야할까?
# 해결: 시그모이드 역함수인 logit함수와 W역행렬계산을 통해 인풋값을 알아내고, 다시 업데이트를 함.

----  I  ---------------
[-0.56765115  0.08109302]
---- W_1 ---------------
[[1. 2.]
 [1. 7.]]
---- W_2 ---------------
[[2. 3.]
 [1. 4.]]
----E_h uppdate_val --------
[-0.00265023 -0.00190637]
---- W_2 Answer ------------
[[2.00265023 3.00190637]
 [1.00265023 4.00190637]]
----E_i Update_val --------
[ 0.00572609 -0.00178343]
---- W_1 Answer ------------
[[0.99427391 2.00178343]
 [0.99427391 7.00178343]]


# 4번 문제 : 3x2x3 순전파

In [5]:
input = np.array([0.9, 0.8], ndmin=2).T
#print(input.shape)
Winput_hidden = np.matrix([[0.9, 0.4], [0.2, 0.2], [0.1, 0.6]])
#print(Winput_hidden.shape)
Whidden_output = np.matrix([[0.3, 0.7, 0.5], [0.8, 0.1, 0.9]])
#print(Whidden_output.shape)

O_j = forward(Winput_hidden, input)
O_k = forward(Whidden_output, O_j)

print(O_k)

[[0.72213297]
 [0.77521169]]


# 5번 문제 : 가중치 업데이트

In [8]:
I = np.array([0.9, 0.1, 0.8], ndmin=2).T 
#print(I.shape)
W_ij = np.array([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])
#print(W_ih.shape)
W_jk = np.array([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])
#print(W_ho.shape)
targets = np.matrix([[0.01],[0.01], [0.99]])
#print(targets.shape)

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def forward(W, I):
    A1 = np.dot(W,I)
    return sigmoid(A1)

O_j = forward(W_ij, I)
O_k = forward(W_jk, O_j)
print("---- 처음 출력값 --------")
print(O_k)

lr = 0.1
step = 1

# 가중치 업데이트 ------------------------------
for i in range(step): 
    #hidden <- output
    E_k = np.array(np.abs(targets - O_k))
    Update_val = lr*(-E_k * O_k*(1- O_k) *O_j.T)
    W_jk = W_jk - Update_val
    #input <- hidden
    E_j = np.dot(W_ij.T, E_k)/(np.sum(W_ij)/2)
    Update_val = lr*(-E_j * O_j*(1- O_j) * I.T)
    W_ij = W_ij - Update_val
# ----------------------------------------------

print("---- W_2 Answer ------------")
print(W_jk)
print("---- W_1 Answer ------------")
print(W_ij)

O_j = forward(W_ij, I)
O_k = forward(W_jk, O_j)

print("---- 최종 출력값 --------")
print(O_k)
print("---- 보기 편하게 --------")
print((O_k*100).astype(int)) #보기편하게 정수형으로 변환 /100하면 실제값

#hidden 레이어로 갈때 정규화를 해라. 1.3이 모두다 되게 해라.??
#2번에서 matrix 나누는 부분만 추가를
#그림을 보고 1,1 어떤 rate값이 분모를 가는지 적용.

---- 처음 출력값 --------
[[0.72630335]
 [0.70859807]
 [0.77809706]]
---- W_2 Answer ------------
[[0.31084074 0.7085931  0.50925857]
 [0.61098232 0.50870533 0.20937949]
 [0.80278553 0.102208   0.90237899]]
---- W_1 Answer ------------
[[0.91317408 0.30146379 0.41171029]
 [0.21894585 0.80210509 0.21684076]
 [0.11132724 0.50125858 0.61006866]]
---- 최종 출력값 --------
[[0.73182933]
 [0.7140752 ]
 [0.7802667 ]]
---- 보기 편하게 --------
[[73]
 [71]
 [78]]


# 201601769 나요한
